# Generated by Django 3.0.1 on 2019-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(max_length=20)),
                ('time_left', models.CharField(max_length=20)),
            ],
        ),
    ]
