# Generated by Django 3.0.1 on 2019-12-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20191221_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
