# Generated by Django 3.0.1 on 2020-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200117_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='name',
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
