# Generated by Django 3.0.1 on 2020-01-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200117_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='time_left',
            new_name='timeLeft',
        ),
    ]
