# Generated by Django 3.0.1 on 2020-01-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200117_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='timeLeft',
            new_name='time_left',
        ),
    ]
